name: clair3
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - absl-py=2.1.0=py310h06a4308_0
  - aiodns=3.5.0=py310h06a4308_0
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.12.15=py310hb25bd0a_0
  - aiosignal=1.4.0=py310h06a4308_0
  - alsa-lib=1.2.14=h5eee18b_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - annotated-types=0.6.0=py310h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - arcp=0.2.1=pyhd8ed1ab_1
  - array-api-compat=1.12.0=pyhe01879c_0
  - arrow-cpp=11.0.0=ha770c72_58_cpu
  - astunparse=1.6.3=py_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attrs=24.3.0=py310h06a4308_0
  - aws-c-auth=0.7.11=h0b4cabd_1
  - aws-c-cal=0.6.9=h14ec70c_3
  - aws-c-common=0.9.12=hd590300_0
  - aws-c-compression=0.2.17=h572eabf_8
  - aws-c-event-stream=0.4.1=h97bb272_2
  - aws-c-http=0.8.0=h9129f04_2
  - aws-c-io=0.14.0=hf8f278a_1
  - aws-c-mqtt=0.10.1=h2b97f5f_0
  - aws-c-s3=0.4.9=hca09fc5_0
  - aws-c-sdkutils=0.1.13=h572eabf_1
  - aws-checksums=0.1.17=h572eabf_7
  - aws-crt-cpp=0.26.0=h04327c0_8
  - aws-sdk-cpp=1.11.210=hba3e011_10
  - biopython=1.85=py310hb25bd0a_0
  - blas=1.0=openblas
  - blosc=1.21.5=h0f2a231_0
  - boost-cpp=1.85.0=h44aadfe_2
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - c-blosc2=2.15.2=h68e2383_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cached-property=2.0.1=py310h06a4308_0
  - cachetools=5.5.1=py310h06a4308_0
  - cairo=1.18.0=hbb29018_2
  - cattrs=24.1.2=py310h06a4308_0
  - certifi=2025.8.3=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - cfgv=3.4.0=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - clair3=1.2.0=py310h779eee5_0
  - click=8.2.1=py310h06a4308_0
  - colorama=0.4.6=py310h06a4308_0
  - coloredlogs=15.0.1=py310h06a4308_3
  - colormath=3.0.0=pyhd8ed1ab_4
  - contourpy=1.3.1=py310hdb19cb5_0
  - coreutils=9.5=h5eee18b_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cryptography=45.0.5=py310hea9ce0a_0
  - curl=8.14.1=h332b0f4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - deprecated=1.2.13=py310h06a4308_0
  - distlib=0.3.8=py310h06a4308_0
  - eido=0.2.4=pyhd8ed1ab_0
  - ensembl-vep=88.9=1
  - exceptiongroup=1.2.0=py310h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py310h06a4308_0
  - filetype=1.2.0=pyhd8ed1ab_0
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py310h5eee18b_0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - future=1.0.0=py310h06a4308_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - git=2.51.0=pl5321h28ef92a_0
  - gitdb=4.0.12=py310h06a4308_0
  - gitpython=3.1.43=py310h06a4308_0
  - glib=2.84.3=h89d24bf_0
  - glib-tools=2.84.3=hf516916_0
  - glog=0.6.0=h6f12383_0
  - google-auth=2.38.0=py310h06a4308_1
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.59.3=py310h1b8f574_0
  - h5py=3.13.0=nompi_py310h60e0fe6_100
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - htslib=1.3.1=h60f3df9_8
  - humanfriendly=10.0=py310h06a4308_2
  - humanize=4.12.2=py310h06a4308_0
  - icu=73.2=h59595ed_0
  - identify=2.5.5=py310h06a4308_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.5.0=py310h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - iniconfig=2.1.0=py310h06a4308_0
  - isa-l=2.31.1=hb9d3cd8_1
  - itsdangerous=2.2.0=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.1=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - kaleido-core=0.2.1=h3644ca4_0
  - kiwisolver=1.4.8=py310h6a678d5_0
  - krb5=1.21.3=h723845a_4
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libaec=1.1.3=h6a678d5_0
  - libarrow=11.0.0=h75ae66a_58_cpu
  - libavif=1.1.1=h5eee18b_0
  - libboost=1.85.0=hba137d9_2
  - libboost-devel=1.85.0=h00ab1b0_2
  - libboost-headers=1.85.0=ha770c72_2
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_4
  - libglib=2.84.3=hf39c6af_0
  - libgomp=15.1.0=h767d61c_4
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.1=hb25bd0a_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=hb3ce162_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb25bd0a_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.09.01=h7a70373_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.7.0=h8261f1e_6
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb25bd0a_0
  - linkify-it-py=2.0.0=py310h06a4308_0
  - llvmlite=0.44.0=py310h6a678d5_0
  - lmdb=0.9.31=hb25bd0a_0
  - logmuse=0.2.8=pyhd8ed1ab_1
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - markdown=3.4.1=py310h06a4308_0
  - markdown-it-py=4.0.0=py310h06a4308_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mathjax=2.7.5=h06a4308_0
  - matplotlib-base=3.10.5=py310h9489213_0
  - mdurl=0.1.0=py310h06a4308_0
  - multidict=6.1.0=py310h5eee18b_0
  - multiqc=1.31=pyhdfd78af_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - mysqlclient=2.2.7=py310h9543f32_0
  - nanofilt=2.8.0=py_0
  - nanoget=1.19.1=pyhdfd78af_0
  - nanomath=1.4.0=pyhdfd78af_0
  - nanoplot=1.46.1=pyhdfd78af_0
  - narwhals=1.31.0=py310h06a4308_1
  - natsort=8.4.0=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.4=pyhd8ed1ab_0
  - nextflow=25.04.6=h2a3209d_0
  - nf-core=3.3.2=pyhdfd78af_0
  - nf-test=0.9.2=h2a3209d_0
  - nodeenv=1.9.1=py310h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.74=h0370c37_0
  - numba=0.61.2=py310h6a678d5_0
  - numexpr=2.11.0=py310hccd6f0b_1
  - numpy=1.26.4=py310hc213724_1
  - numpy-base=1.26.4=py310hf387b04_1
  - oauthlib=3.3.1=py310h06a4308_0
  - openjdk=17.0.14=he4ca013_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.5.2=h26f9b46_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - orc=1.9.2=h4b38347_0
  - oyaml=1.0=pyhd8ed1ab_0
  - packaging=25.0=py310h06a4308_0
  - pandas=1.5.3=py310h9b08913_1
  - pango=1.50.7=h668f713_2
  - parallel=20160622=1
  - patsy=1.0.1=py310h06a4308_0
  - pbzip2=1.1.13=h1fcc475_2
  - pcre2=10.45=hc749103_0
  - peppy=0.40.7=pyhd8ed1ab_0
  - perl=5.22.0.1=0
  - perl-bio-db-hts=2.4=0
  - perl-bioperl=1.6.924=4
  - perl-cgi=4.22=3
  - perl-common-sense=3.74=0
  - perl-compress-raw-bzip2=2.069=1
  - perl-compress-raw-zlib=2.069=3
  - perl-dbd-mysql=4.033=2
  - perl-dbi=1.641=pl5.22.0_0
  - perl-io-compress=2.069=1
  - perl-json=2.90=1
  - perl-json-xs=2.34=0
  - perl-perlio-gzip=0.19=0
  - perl-scalar-list-utils=1.45=2
  - perl-sereal=3.015=0
  - perl-sereal-decoder=3.015=0
  - perl-sereal-encoder=3.015=0
  - perl-set-intervaltree=0.10=3
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-yaml=1.24=pl522_1
  - pigz=2.8=hadc24fc_1
  - pillow=11.0.0=py310hfeaa1f3_0
  - pip=25.1=pyhc872135_2
  - piper=0.14.4=pyhdfd78af_0
  - pipestat=0.12.1=pyhd8ed1ab_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py310h06a4308_0
  - plotly=6.3.0=py310he3bba80_0
  - pluggy=1.5.0=py310h06a4308_0
  - polars-lts-cpu=1.32.3=py39h5734d0f_0
  - pre-commit=3.4.0=py310h06a4308_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py310h5eee18b_0
  - psutil=5.9.0=py310h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pulp=3.2.2=py310h06a4308_0
  - py-cpuinfo=9.0.0=py310h06a4308_0
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py310h468efa6_1
  - pyasn1=0.6.1=py310h06a4308_0
  - pyasn1-modules=0.4.2=py310h06a4308_0
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py310h06a4308_0
  - pydantic-core=2.33.2=py310hc6f7160_0
  - pyfaidx=0.9.0.1=pyhdfd78af_0
  - pygithub=2.4.0=py310h06a4308_0
  - pygments=2.19.1=py310h06a4308_0
  - pyjwt=2.10.1=py310h06a4308_0
  - pynacl=1.5.0=py310h5eee18b_1
  - pynndescent=0.5.13=py310h06a4308_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pysam=0.23.3=py310h64e62c9_1
  - pysocks=1.7.1=py310h06a4308_0
  - pytables=3.9.2=py310h73b55d5_3
  - pytest=8.4.1=py310h06a4308_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-dotenv=1.1.0=py310h06a4308_0
  - python-flatbuffers=24.3.25=py310h06a4308_0
  - python-gil=3.10.18=hd8ed1ab_0
  - python-isal=1.7.2=py310ha75aee5_0
  - python-kaleido=0.2.1=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-zlib-ng=0.5.1=py310h62b3d1f_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=py310h06a4308_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - questionary=2.1.0=pyhd8ed1ab_2
  - rdma-core=58.0=h7934f7d_0
  - re2=2023.09.01=h7f4b329_1
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py310h06a4308_0
  - refgenconf=0.12.2=pyhdfd78af_0
  - refgenie=0.12.1=pyhdfd78af_0
  - regex=2024.11.6=py310h5eee18b_0
  - repo2rocrate=0.1.2=pyhd8ed1ab_0
  - requests=2.32.4=py310h06a4308_0
  - requests-cache=1.2.0=py310h06a4308_0
  - requests-oauthlib=2.0.0=py310h06a4308_0
  - rich=13.9.4=py310h06a4308_0
  - rich-click=1.8.9=pyhd8ed1ab_0
  - rocrate=0.14.0=pyhd8ed1ab_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - ruamel.yaml=0.18.10=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py310h5eee18b_0
  - s2n=1.4.1=h06160fa_0
  - samtools=1.6=h5fe306e_12
  - scanpy=1.7.2=pyhdfd78af_0
  - scikit-learn=1.7.1=py310hc74f9fe_0
  - scipy=1.15.3=py310h5e4e545_0
  - seaborn=0.13.2=py310h06a4308_3
  - setuptools=78.1.1=py310h06a4308_0
  - setuptools-scm=8.3.1=py310h06a4308_1
  - setuptools_scm=8.3.1=hd3eb1b0_1
  - shellingham=1.5.0=py310h06a4308_0
  - sinfo=0.3.1=py_0
  - six=1.17.0=py310h06a4308_0
  - smmap=5.0.2=py310h06a4308_0
  - snappy=1.1.10=h6a678d5_1
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.50.4=hbc0de68_0
  - statsmodels=0.14.5=py310h76ea63d_0
  - stdlib-list=0.10.0=py310h06a4308_0
  - tabulate=0.9.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.1.0=py310h06a4308_0
  - textual=0.71.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tiktoken=0.9.0=py310h52b74c6_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=py310h06a4308_0
  - tqdm=4.67.1=py310h2f386ee_0
  - trogon=0.6.0=pyhd8ed1ab_1
  - typeguard=4.2.1=py310h06a4308_0
  - typer=0.9.0=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing-inspection=0.4.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - uc-micro-py=1.0.1=py310h06a4308_0
  - ucx=1.15.0=ha691c75_8
  - ujson=5.10.0=py310h6a678d5_1
  - ukkonen=1.0.1=py310hdb19cb5_1
  - umap-learn=0.5.3=py310h06a4308_0
  - unicodedata2=15.1.0=py310h5eee18b_1
  - unzip=6.0=h611a1e1_0
  - url-normalize=1.4.3=py310h06a4308_0
  - urllib3=2.5.0=py310h06a4308_0
  - uvloop=0.21.0=py310h5eee18b_0
  - veracitools=0.1.3=py_0
  - virtualenv=20.28.0=py310h06a4308_0
  - wcwidth=0.2.13=py310h06a4308_0
  - werkzeug=3.1.3=py310h06a4308_0
  - whatshap=2.8=py310h184ae93_0
  - wheel=0.45.1=py310h06a4308_0
  - wrapt=1.14.1=py310h5eee18b_0
  - xopen=2.0.2=pyh707e725_2
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yacman=0.9.3=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zipp=3.21.0=py310h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - boto3==1.40.25
      - botocore==1.40.25
      - choreographer==1.0.10
      - gast==0.4.0
      - google-auth-oauthlib==0.4.6
      - jmespath==1.0.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - logistro==1.1.0
      - ml-dtypes==0.5.3
      - namex==0.1.0
      - optree==0.17.0
      - orjson==3.11.3
      - protobuf==3.19.6
      - python-graphviz==0.21
      - s3transfer==0.13.1
      - simplejson==3.20.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
variables:
  LD_LIBRARY_PATH: /N/soft/rhel8/gcc/14.2.0/lib64:/N/soft/rhel8/gcc/14.2.0/lib64:/N/soft/rhel8/mvapich/gnu/2.3.5/lib:/N/soft/rhel8/gcc/9.3.0/lib64:/N/soft/rhel8/gcc/9.3.0/lib
prefix: /N/u/sidrajes/Quartz/.conda/envs/clair3